#!/bin/sh

# This test needs files from the corresponding cura release:
# cp $cura_sourcedir/resources/definitions/fdmprinter.def.json debian/tests
# cp $cura_sourcedir/resources/definitions/fdmextruder.def.json debian/tests

set -ex

CuraEngine slice -j debian/tests/fdmprinter.def.json -l tests/testModel.stl -o ${AUTOPKGTEST_TMP:-/tmp}/foo.gcode
